# Generated by Django 3.1.1 on 2020-10-20 18:08

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201011_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='doctor',
        ),
        migrations.AddField(
            model_name='customer',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='speciality',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dentist', 'Dentist'), ('hygienist', 'Hygienist'), ('surgeon', 'Surgeon'), ('assistant', 'Assistant')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
