# Generated by Django 3.1.1 on 2020-10-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20201020_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='employee',
        ),
        migrations.AddField(
            model_name='customer',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.employee'),
        ),
    ]
