# Generated by Django 3.1.1 on 2020-09-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200913_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
