# Generated by Django 3.1.1 on 2020-10-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20201026_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='employee',
        ),
        migrations.AddField(
            model_name='customer',
            name='employee',
            field=models.ManyToManyField(to='website.Employee'),
        ),
    ]
