# Generated by Django 3.1.1 on 2020-09-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_staffprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'staff_profile', 'verbose_name_plural': 'staff_profiles'},
        ),
    ]
