# Generated by Django 3.1.1 on 2020-09-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200913_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='full_name',
        ),
    ]
