# Generated by Django 3.1.1 on 2020-09-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_staffprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='updated_date',
        ),
    ]
