# Generated by Django 3.1.1 on 2020-09-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200913_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'staff profile', 'verbose_name_plural': 'staff profiles'},
        ),
    ]
