# Generated by Django 3.1.1 on 2020-09-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200917_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='email',
        ),
    ]
