# Generated by Django 3.1.1 on 2020-09-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200917_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Customer',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
    ]
