# Generated by Django 3.1.1 on 2020-09-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20200920_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('-', '-'), ('M', 'Male'), ('F', 'Female')], default='-', max_length=1),
        ),
    ]
